### ISSUE TITLE
add dynamic Card for subjects

### ISSUE THREAD

**Issue by Saigenix** [Saigenix/Study-planner#2]
Now on the website, there are limited Subjets to add details means we can only add details about three subjects I want to make that dynamic that means we can details of as many subjects

**Comment by ishita1805** [comment]
Hi, I'd like to pick this up!

**Comment by Saigenix** [comment]
ok i will assign to you

**Comment by ishita1805** [comment]
@Saigenix My PR is ready for review, lemme know what you think

**Comment by Saigenix** [comment]
@ishita1805 I merged it! Again thanks for your great work  

ps : plz look on delete section btn

**Comment by Saigenix** [comment]
@ishita1805  that problem is happening because of the form tag in HTML I removed that tag now the site is not redirecting anywhere

**Comment by ishita1805** [comment]
I've added a PR to fix this, you can check it out here: https://github.com/Saigenix/Study-planner/pull/6

**Comment by Saigenix** [comment]
@ishita1805 Thanks! if you want any help let me know!

and if you're a cs student then I request you to join my channel on telegram 
https://t.me/csitclub
